#
# Site settings
#
title: Ideance
url: https://ideance-a11y.github.io/
baseurl: /rgaa4-impacts-utilisateurs
author: Ideance

exclude: ['README.md', 'Gemfile.lock', 'Gemfile']

theme: null

sass:
    sass_dir: _sass
    style: expanded
    sourcemap: development

markdown: GFM